version: "3.8"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload

    environment:
      - DATABASE_TYPE=postgresql
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=110963
      - DATABASE_NAME=fastapi
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=0d589fdbd2db8beede8220a45e0d5eeac5f79150ae266b2cf9f84ec598fe8709
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=110963
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres-db:

